title: Flying Dice LLC
author: Andrew Hawker
email: andrew@flyingdice.dev
description: Website for Flying Dice LLC
baseurl:
permalink: /:categories/:year/:month/:day/:title/
url: https://flyingdice.dev
twitter_username: flyingdicellc
github_username:  flyingdice

# Jekyll SEO
# https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
twitter:
  card: summary
  username: flyingdicellc
logo: /assets/images/logo.png
social:
  name: Flying Dice
  links:
  - https://github.com/flyingdice
  - https://twitter.com/flyingdicellc

# Jekyll Archives
# https://github.com/jekyll/jekyll-archives/blob/master/docs/configuration.md
jekyll-archives:
  enabled:
    - year
    - tags
    - categories
  permalinks:
    year: '/archives/year/:year/'
    tag: '/archives/tag/:name/'
    category: '/archives/category/:name/'
  layout: archive

sass:
  style: compressed

markdown: kramdown

plugins:
  - jekyll-archives
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - package-lock.json
  - README.md
  - Makefile
  - .git
  - .gitignore
  - yarn.lock
  - yarn-error.log
  - node_modules

ga_tracking_id: G-F6R1HK4BQ0

defaults:
  - scope:
      path: ''
      type: posts
    values:
      image: /assets/images/logo.png
